<?php
// fields for Advance Custom Fields Plugin
// http://www.advancedcustomfields.com

if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_541a3e10b6c89',
	'title' => 'Footer',
	'fields' => array (
		array (
			'key' => 'field_541a3e4b9129b',
			'label' => 'New York Address',
			'name' => 'ny-address',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => 'Add the address and contact information for New York',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 1,
			'max' => 1,
			'layout' => 'row',
			'button_label' => 'Add Address',
			'sub_fields' => array (
				array (
					'key' => 'field_541a3ef89129c',
					'label' => 'Street',
					'name' => 'street',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add a street address',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'street',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a3f589129d',
					'label' => 'Floor or suite',
					'name' => 'floor',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add the floor or suite.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Floor or suite',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a3faf9129e',
					'label' => 'City',
					'name' => 'city',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add the city',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'City',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a3fca9129f',
					'label' => 'State',
					'name' => 'state',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add the state',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'State',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a3fe9912a0',
					'label' => 'Zip code',
					'name' => 'zip-code',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add the zip code ',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Zip code',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a401b912a1',
					'label' => 'Phone',
					'name' => 'phone',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add a phone number',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '(xxx) xxx-xxxx',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a4046912a2',
					'label' => 'Fax',
					'name' => 'fax',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add a fax number',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '(xxx) xxx-xxxx',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_541a4188853a1',
			'label' => 'LA Address',
			'name' => 'la-address',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => 'Add the address and contact information for LA',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 1,
			'max' => 1,
			'layout' => 'row',
			'button_label' => 'Add Address',
			'sub_fields' => array (
				array (
					'key' => 'field_541a4189853a2',
					'label' => 'Street',
					'name' => 'street',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add a street address',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'street',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a4189853a3',
					'label' => 'Floor or suite',
					'name' => 'floor',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add the floor or suite.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Floor or suite',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a4189853a4',
					'label' => 'City',
					'name' => 'city',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add the city',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'City',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a4189853a5',
					'label' => 'State',
					'name' => 'state',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add the state',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'State',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a4189853a6',
					'label' => 'Zip code',
					'name' => 'zip-code',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add the zip code ',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Zip code',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a4189853a7',
					'label' => 'Phone',
					'name' => 'phone',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add a phone number',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '(xxx) xxx-xxxx',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_541a4189853a8',
					'label' => 'Fax',
					'name' => 'fax',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Add a fax number',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '(xxx) xxx-xxxx',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_541a4075912a3',
			'label' => 'Copyright',
			'name' => 'copyright',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add the copyright text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Copyright © 2014 Wasserstein & Co., All Rights Reserved',
			'placeholder' => 'Copyright © 2014 Wasserstein & Co., All Rights Reserved',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-footer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_541b8ddea15d0',
	'title' => 'Home',
	'fields' => array (
		array (
			'key' => 'field_541b8df1d414b',
			'label' => 'Intro Image',
			'name' => 'intro_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Upload an intro image for the home page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array (
			'key' => 'field_541b8ed1d414d',
			'label' => 'Intro text',
			'name' => 'intro_text',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => 'Enter intro text to display under the image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_541b8e2dd414c',
			'label' => 'Call to action link',
			'name' => 'intro_cta',
			'prefix' => '',
			'type' => 'page_link',
			'instructions' => 'Select a page link for the intro',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '5',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
));

register_field_group(array (
	'key' => 'group_542603f26d7f4',
	'title' => 'Investments',
	'fields' => array (
		array (
			'key' => 'field_542606f63661f',
			'label' => 'Current or Past',
			'name' => 'current',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Is this a current investment or past investment?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'current' => 'Current Investment',
				'past' => 'Past Investment',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_5426042b5b2af',
			'label' => 'Logo',
			'name' => 'logo',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Add a logo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array (
			'key' => 'field_5426045c5b2b0',
			'label' => 'Intro',
			'name' => 'intro',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => 'Add intro text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5445731467013',
			'label' => 'Fund',
			'name' => 'fund',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add fund',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_542605a05b2b3',
			'label' => 'Initial Investment',
			'name' => 'initial_investment',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add an initial investment data',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_543f33e8a9e1f',
			'label' => 'Entry',
			'name' => 'entry',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add entry year — CURRENTLY NOT DISPLAYED ON FRONT-END',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_543f3407a9e20',
			'label' => 'Exit',
			'name' => 'exit',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add exit year',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5426056f5b2b2',
			'label' => 'URL',
			'name' => 'url',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add a URL',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_542604ed5b2b1',
			'label' => 'Full Description',
			'name' => 'full_description',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Add the full description',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_542606075b2b5',
			'label' => 'Image',
			'name' => 'image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Add an image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array (
			'key' => 'field_542605e95b2b4',
			'label' => 'Second Image',
			'name' => 'second_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Add the second image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wsc_investments',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_541df2a35989a',
	'title' => 'Page Layouts',
	'fields' => array (
		array (
			'key' => 'field_541df2dcc59ee',
			'label' => 'Intro Layout',
			'name' => 'intro',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => 'Select the intro module for the page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Layout',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '541df3050d05d',
					'name' => 'image',
					'label' => 'Image Intro',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_541df37fc59ef',
							'label' => 'Image',
							'name' => 'image',
							'prefix' => '',
							'type' => 'image',
							'instructions' => 'Select an image of the intro',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
					),
					'min' => 0,
					'max' => 1,
				),
				array (
					'key' => '541df3cfc59f0',
					'name' => 'text',
					'label' => 'Text Intro',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_541df3e5c59f1',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'textarea',
							'instructions' => 'Enter intro text',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'br',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => 0,
					'max' => 1,
				),
				array (
					'key' => '5428847fd5af1',
					'name' => 'extended',
					'label' => 'Extended Intro',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_542884b5d5af2',
							'label' => 'Additional Text',
							'name' => 'additional',
							'prefix' => '',
							'type' => 'textarea',
							'instructions' => 'Add additional text ',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'br',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => 1,
				),
				array (
					'key' => '5431a48bb2de8',
					'name' => 'subhead',
					'label' => 'Subhead Intro',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5431a4abb2de9',
							'label' => 'Subhead Text',
							'name' => 'subhead_text',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Add a intro subhead',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_541df8782decf',
			'label' => 'Page Layout',
			'name' => 'layout',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => 'Select the layout modules for the page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Layout',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '541df3050d05d',
					'name' => 'standard',
					'label' => 'Standard with images',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_541df8782ded0',
							'label' => 'Horizontal Image',
							'name' => 'h_image',
							'prefix' => '',
							'type' => 'image',
							'instructions' => 'Select a horizontal image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
						array (
							'key' => 'field_541f7261ae41c',
							'label' => 'Vertical Image',
							'name' => 'v_image',
							'prefix' => '',
							'type' => 'image',
							'instructions' => 'Select a vertical image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
						array (
							'key' => 'field_541f7295ae41d',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => 'Add text for the page',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'visual',
							'toolbar' => 'basic',
							'media_upload' => 1,
						),
					),
					'min' => 0,
					'max' => 1,
				),
				array (
					'key' => '541f8a942cfa4',
					'name' => 'history',
					'label' => 'History Module',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_541f8aa12cfa5',
							'label' => 'Image',
							'name' => 'image',
							'prefix' => '',
							'type' => 'image',
							'instructions' => 'Add image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
						array (
							'key' => 'field_541f8da270f84',
							'label' => 'Title',
							'name' => 'title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Add a title for this module',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_541f8bee2cfa6',
							'label' => 'Column One',
							'name' => 'c_one',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => 'Enter text for the first column',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'visual',
							'toolbar' => 'basic',
							'media_upload' => 0,
						),
						array (
							'key' => 'field_541f8c3f2cfa7',
							'label' => 'Column Two',
							'name' => 'c_two',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'visual',
							'toolbar' => 'basic',
							'media_upload' => 0,
						),
					),
					'min' => 0,
					'max' => 1,
				),
				array (
					'key' => '542461ec39f15',
					'name' => 'team_module',
					'label' => 'Team Module',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_542461f939f16',
							'label' => 'Select Team',
							'name' => 'select_team',
							'prefix' => '',
							'type' => 'radio',
							'instructions' => 'Select a team',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'wp' => 'Wasserstein Partners',
								'wdo' => 'Wasserstein Debt Opportunites',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => 1,
				),
				array (
					'key' => '54260b8defa8d',
					'name' => 'investments',
					'label' => 'Investments',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54260bb6efa8e',
							'label' => 'Show Investments',
							'name' => 'show_investments',
							'prefix' => '',
							'type' => 'checkbox',
							'instructions' => 'Check the box to display both current and past investments',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'true' => 'Show Investments',
							),
							'default_value' => array (
							),
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => 1,
				),
				array (
					'key' => '54286e1c9f0eb',
					'name' => 'tab_module',
					'label' => 'Tab Module',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5428713b29a99',
							'label' => 'Tabs',
							'name' => 'tabs',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => 'Add tabs',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'row',
							'button_label' => 'Add Tab',
							'sub_fields' => array (
								array (
									'key' => 'field_542871d029a9a',
									'label' => 'Tab title',
									'name' => 'tab_title',
									'prefix' => '',
									'type' => 'text',
									'instructions' => 'Add a title for this tab',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_542871ed29a9b',
									'label' => 'Tab Text',
									'name' => 'tab_text',
									'prefix' => '',
									'type' => 'wysiwyg',
									'instructions' => 'Add text for this tab',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'visual',
									'toolbar' => 'basic',
									'media_upload' => 0,
								),
								array (
									'key' => 'field_5428720929a9c',
									'label' => 'Bullets',
									'name' => 'bullets',
									'prefix' => '',
									'type' => 'repeater',
									'instructions' => 'Add bullets',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'min' => '',
									'max' => '',
									'layout' => 'table',
									'button_label' => 'Add Bullet',
									'sub_fields' => array (
										array (
											'key' => 'field_5428721d29a9d',
											'label' => 'Bullet Title',
											'name' => 'bullet_title',
											'prefix' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
										array (
											'key' => 'field_5428722929a9e',
											'label' => 'Bullet Text',
											'name' => 'bullet_text',
											'prefix' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
									),
								),
							),
						),
					),
					'min' => '',
					'max' => 1,
				),
				array (
					'key' => '54298602cd46d',
					'name' => 'news_list',
					'label' => 'News List',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5429861acd46e',
							'label' => 'Show News',
							'name' => 'show_news',
							'prefix' => '',
							'type' => 'checkbox',
							'instructions' => 'Click to show a list of news posts',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'true' => 'Show News',
							),
							'default_value' => array (
							),
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => 1,
				),
				array (
					'key' => '5429a00217a52',
					'name' => 'two_up',
					'label' => '2up Boxes',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5429a00d17a53',
							'label' => 'Boxes',
							'name' => 'boxes',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => 'Add images and text for each box',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => 2,
							'max' => 2,
							'layout' => 'row',
							'button_label' => 'Add Box',
							'sub_fields' => array (
								array (
									'key' => 'field_5429a03817a54',
									'label' => 'Image',
									'name' => 'image',
									'prefix' => '',
									'type' => 'image',
									'instructions' => 'Add image',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
								),
								array (
									'key' => 'field_5429a0b117a59',
									'label' => 'Image Link',
									'name' => 'image_link',
									'prefix' => '',
									'type' => 'text',
									'instructions' => 'Add url image will link to',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5429a05a17a55',
									'label' => 'Title',
									'name' => 'title',
									'prefix' => '',
									'type' => 'text',
									'instructions' => 'Add box title',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5429a09817a58',
									'label' => 'Text',
									'name' => 'text',
									'prefix' => '',
									'type' => 'wysiwyg',
									'instructions' => 'Add box text',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'visual',
									'toolbar' => 'basic',
									'media_upload' => 0,
								),
								array (
									'key' => 'field_5429a06d17a56',
									'label' => 'Link Name',
									'name' => 'link_name',
									'prefix' => '',
									'type' => 'text',
									'instructions' => 'Add link name',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5429a08017a57',
									'label' => 'Link URL',
									'name' => 'link_url',
									'prefix' => '',
									'type' => 'text',
									'instructions' => 'Add link url',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => 1,
				),
				array (
					'key' => '542dcc21e99c0',
					'name' => 'two_column',
					'label' => 'Two Column',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_542dcc2de99c1',
							'label' => 'Column One',
							'name' => 'column_one',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => 'Add text for column one',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'visual',
							'toolbar' => 'full',
							'media_upload' => 0,
						),
						array (
							'key' => 'field_542dcc87e99c2',
							'label' => 'Column Two',
							'name' => 'column_two',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => 'Add text for column two',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'visual',
							'toolbar' => 'full',
							'media_upload' => 0,
						),
					),
					'min' => '',
					'max' => 1,
				),
				array (
					'key' => '54298651cd46f',
					'name' => 'press_list',
					'label' => 'Press List',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54298659cd470',
							'label' => 'Show Press',
							'name' => 'show_press',
							'prefix' => '',
							'type' => 'checkbox',
							'instructions' => 'Click to show a list of press releases',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'true' => 'Show Press',
							),
							'default_value' => array (
							),
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => 1,
				),
				array (
					'key' => '54811cc1e6dc8',
					'name' => 'text_only',
					'label' => 'Text Only',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54811cd2e6dc9',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => 'Add text',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => 1,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'featured_image',
		9 => 'categories',
		10 => 'tags',
		11 => 'send-trackbacks',
	),
));

register_field_group(array (
	'key' => 'group_5424596aaba33',
	'title' => 'Team',
	'fields' => array (
		array (
			'key' => 'field_54245c0b2fd6e',
			'label' => 'Group',
			'name' => 'group',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Select a group for this bio',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'wp' => 'Wasserstein Partners',
				'wdo' => 'Wasserstein Debt Opportunities',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_543f40826205f',
			'label' => 'Last Name',
			'name' => 'last_name',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add a last name for the menu order.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54245970579fe',
			'label' => 'Position',
			'name' => 'position',
			'prefix' => '',
			'type' => 'taxonomy',
			'instructions' => 'Select a position',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'position',
			'field_type' => 'select',
			'allow_null' => 0,
			'load_save_terms' => 1,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_54245b1b579ff',
			'label' => 'Portrait',
			'name' => 'portrait',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Select a portrait image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array (
			'key' => 'field_54245b3757a00',
			'label' => 'Bio',
			'name' => 'bio',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Enter bio text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wsc_team',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'categories',
		1 => 'tags',
	),
));

endif;